### ISSUE TITLE
mksdcard.sh script does not work on Ubuntu 14.04 with missing /dev/disk/by-path

### ISSUE THREAD

**Issue by discretepackets** [boundarydevices/android_device_boundary#2]
I have a relatively clean install of Ubuntu 14.04 that for some reason does not have /dev/disk/by-path and this script will fail to run because it attempts to access /dev/disk/by-path:

https://github.com/boundarydevices/android_device_boundary/blob/boundary-kk4.4.2_1.0.0-ga/mksdcard.sh#L27

I'm not entirely sure what causes /dev/disk/by-path to be missing. Interestingly, I recall that my previous install of Ubuntu 14.04 on a different computer didn't have this issue.

Some reference for missing /dev/disk/by-path issue:
http://www.dslreports.com/forum/r28988943-Upgraded-ubuntu-dev-disk-by-path-now-missing-disks
https://bugs.launchpad.net/ubuntu/+source/udev/+bug/1391427

It would be great if this script can be updated to not rely on /dev/disk/by-path!

**Comment by discretepackets** [comment]
I just bought an external SD card reader to test this out:

Here's my latest discovery:

For this laptop I'm using, the laptop internal SD card reader shows up as /dev/mmcblk0 and Ubuntu doesn't generate the corresponding /dev/disk/by-path. However, if I plug in an external SD card reader, the SD card reader shows up as /dev/sde and the corresponding /dev/disk/by-path is created.

I'm not that familiar with Linux/Ubuntu to understand what's going on with /dev/disk/by-path but my guess is that depending on the hardware configuration of the host computer, /dev/disk/by-path might or might not show up.

**Comment by ericnelsonaz** [comment]
Interesting. Can you try replacing by-path/ with by-id/?

**Comment by discretepackets** [comment]
Yeah it appears to work when I change it to by-id.

I can't confirm because there's a potentially related error: I can't create the 8th partition on the SD card. The script will report back "missing /dev/mmcblk0p8" even though earlier in the script it says "Successfully wrote the new partition table"

I don't have this problem if I use the external SD card reader on the same computer. It could be related to the 4-partition limit on Linux that applies to /dev/mmcblk0 devices instead of /dev/sdX devices.

**Comment by discretepackets** [comment]
(I would like to contribute a fix but unfortunately I'm just starting out with shell scripting, embedded Linux, etc to really know what's going on.)
