### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by IngenicC** [boundarydevices/android_device_boundary#7]
hello，
      I  build  source  code，but  the  launcher  is  different  from  you，which  launcher  do  you  choose，I  get  the  source  from google，I  build  android 6 and  7 ，it  seems the  launcher  are  all  the same，it is
so  ugly
                                                                                                                                      thanks！

**Comment by gibsson** [comment]
Hi,

The default launcher is Launcher2 but you can enable Launcher3 with no problem.
http://androidxref.com/7.1.1_r6/xref/packages/apps/Launcher3/

Regards,
Gary

**Comment by IngenicC** [comment]
Thanks  for your  replies
          how  to  enable Launcher2,I  use  PRODUCT_PACKAGES +=Launcher2 ,but It  seems  that  it  does't work,It  still  use  default  Launcher  ，the Launcher layout is different from https://boundarydevices.com/android-nougat-7-1-1-release-imx6-boards/

**Comment by gibsson** [comment]
Sorry but I don't understand your issue. In the first message you say:
"I build source code，but the launcher is different from you"
Which Launcher do you use? Which one do you want? Launcher2 is the one provided in our images and the default one.
Can you send a picture of yours?
Which platform do you use?
Which display do you use?

Regards,
Gary
